image: fedora:rawhide

pages:
  script:
  - dnf install -y cmake doxygen graphviz mscgen make gcc gcc-c++ kernel-devel
  - dnf install -y clang ocl-icd clinfo opencl-headers opencl-filesystem opencl-utils
  - dnf install -y mesa-libOpenCL boost
  - export CC=/usr/bin/clang && export CXX=/usr/bin/clang++
  - mkdir -p build && cd build
  - cmake ..
  - make doc
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
