image: gcc

pages:
  script:
  - apt-get -qq update
  - apt-get -qq install -y cmake
  - apt-get -qq install -y doxygen
  - apt-get -qq install -y ttf-freefont graphviz mscgen
  - mkdir -p build && cd build
  - cmake ..
  - make doc
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
