image: fedora:rawhide

pages:
  script:
  - dnf install -y cmake doxygen graphviz mscgen make gcc gcc-c++ kernel-devel clang ocl-icd clinfo
  - export CC=/usr/bin/clang && export CXX=/usr/bin/clang++
  - mkdir -p build && cd build
  - cmake ..
  - make doc
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
