image: fedora:rawhide

before script:
- dnf update
- dnf install -y cmake
- dnf install -y doxygen
- dnf install -y ttf-freefont graphviz mscgen

pages:
  script:
  - mkdir -p build && cd build
  - cmake ..
  - make doc
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
