image: fedora:rawhide

pages:
  script:
  - dnf install -y cmake doxygen graphviz mscgen
  - mkdir -p build && cd build
  - cmake ..
  - make doc
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
